project:
  type: book
  
lang: pl

book:
  title: "Metody przetwarzania i analizy danych"
  author: "Łukasz Wawrowski"
  date: "04/07/2026"
  favicon: favicon.png
  chapters:
    - index.qmd
    - instalacja.qmd
    - dane.qmd
    - regresja.qmd
    - klasyfikacja.qmd
    - grupowanie.qmd

format:
  html:
    theme: cosmo